name: Build Extensions
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: infera
      enable_rust: true
      exclude_archs: "linux_amd64_musl;windows_amd64_mingw;osx_amd64;wasm_mvp;wasm_eh;wasm_threads"

  duckdb-stable-build:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4.0
    with:
      duckdb_version: v1.4.0
      ci_tools_version: v1.4.0
      extension_name: infera
      enable_rust: true
      exclude_archs: "linux_amd64_musl;windows_amd64_mingw;osx_amd64;wasm_mvp;wasm_eh;wasm_threads"
